admin_panel_index:
    path: /
    defaults:
        _controller: admin.controller.admin:indexAction

admin_panel_locale:
    path: /locale/{_locale}
    defaults:
        _controller: admin.controller.admin:localeAction


admin_panel_list:
    path: /list/{element}
    defaults:
        _controller: admin.controller.list:listAction

admin_panel_batch:
    path: /batch/{element}
    defaults:
        _controller: admin.controller.batch:batchAction

admin_panel_resource:
    path: /resource/{element}
    defaults:
        _controller: admin.controller.resource:resourceAction

