language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.0
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.0
          env:
              - COMPOSER_FLAGS=''

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer update $COMPOSER_FLAGS

script:
    - ./bin/phpspec run --format=pretty
    - ./bin/phpunit

