language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer update

script:
    - ./bin/phpspec run --format=pretty
    - ./bin/phpunit

